services:
  app:
    image: todo-backend
    build: .
    ports:
      - 3000:3000


# `docker compose up` to build and run the application (display logs)
# `docker compose --build` to rebuild the images without running the application
# `docker compose up -d` to build and run the application in the background
# `docker compose down` to stop and remove all containers and resources